sudo: false
language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
node_js:
  - 8
before_install:
  - npm install -g npm@'>=3.5.1'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test:cov
after_script:
  - npm install coveralls && cat ./tests/__coverage__/lcov.info | coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
