sudo: false
branches:
  only:
    - master
language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
    - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
node_js:
  - 10
cache:
  yarn: true
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - greenkeeper-lockfile-update
script:
  - yarn test:cov
after_script:
  - yarn add coveralls && ./node_modules/.bin/coveralls < ./coverage/lcov.info
  - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
  - ./cc-test-reporter upload-coverage
  - greenkeeper-lockfile-upload
